feat: Run tests in Docker
radix-ai/poetry-cookiecutter pull request #63
Opened 2022-06-18 22:02 UTC by sinopeus

- Build Docker CI image
- Run tests in built Docker CI image
- Use GitHub Actions Docker cache to speed up future Docker builds
- Drive-by action upgrades :-)

2022-06-18 22:06 UTC, sinopeus commented
Still need to fix private package repo support + other things that are a bit broken. But that will be for another time, just wanted to put this out there 🙂

2022-06-20 08:06 UTC, lsorber commented
> Still need to fix private package repo support + other things that are a bit broken. But that will be for another time, just wanted to put this out there 🙂

OK, let me know when it's ready for review!

2022-06-20 10:41 UTC, lsorber requested changes
Thanks for the PR! I know it's not ready yet, but I already did a first review pass.

2022-06-20 10:41 UTC, lsorber commented on {{ cookiecutter.package_name|slugify }}/.github/workflows/test.yml
> +        uses: docker/setup-buildx-action@v2
For my information: why is this action needed? I believe `docker/build-push-action` already uses BuildKit, if that's the reason.

2022-06-20 10:41 UTC, lsorber commented on {{ cookiecutter.package_name|slugify }}/.github/workflows/test.yml
> +          target: dev
Shouldn't we be building `ci` here? The `dev` image is much larger because it contains developer tools that in principle aren't necessary in CI.

2022-06-20 10:41 UTC, lsorber commented on {{ cookiecutter.package_name|slugify }}/.github/workflows/test.yml
> -        python-version: ["{{ cookiecutter.python_version }}"]
Although I'm all for using Docker, we do have to be aware that this PR removes the ability to test in a matrix, which is a bit of a downgrade for Python packages (for Python applications that shouldn't matter too much).

2022-06-20 10:41 UTC, lsorber commented on {{ cookiecutter.package_name|slugify }}/.github/workflows/test.yml
> +            ghcr.io/${{ github.repository }}/ci:${{ github.sha }}
What is this SHA based on? Shouldn't we base it off of `Dockerfile`, `poetry.lock`, and `pyproject.toml` as we do in GitLab CI/CD?

2022-06-20 10:41 UTC, lsorber commented on {{ cookiecutter.package_name|slugify }}/.github/workflows/{% if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}deploy.yml{% endif %}
> -          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
We need the `{% raw %}` bits here because otherwise Cookiecutter will treat these as values that should be interpolated.

2022-08-08 17:28 UTC, closed without merging